openapi: 3.0.0
info:
  title: Face Photo Api
  version: 1.0.0
servers:
- url: https://d5dr66gcjebi2sapbcvg.apigw.yandexcloud.net
paths:
  /face.jpg:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: itis-2022-2023-vvot17-faces
        object: '{face}'
        error_object: error.html
        presigned_redirect: true
        service_account_id: ajeh5up8aaotm8spuro1
      parameters:
      - explode: true
        in: query
        name: face
        required: true
        schema:
          type: string
        style: form
      responses:
        '200':
          content:
            image/jpeg:
              schema:
                format: binary
                type: string
          description: OK
  /photo.jpg:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: itis-2022-2023-vvot17-photos
        object: '{photo}'
        error_object: error.html
        presigned_redirect: true
        service_account_id: ajeh5up8aaotm8spuro1
      parameters:
      - explode: true
        in: query
        name: photo
        required: true
        schema:
          type: string
        style: form
      responses:
        '200':
          content:
            image/jpeg:
              schema:
                format: binary
                type: string
          description: OK
